ERROR - 2023-09-25 02:18:38 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'valdivia_j' in C:\xampp\htdocs\tpintegrador\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\tpintegrador\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'valdivia_j', 3306, '', 0)
#1 C:\xampp\htdocs\tpintegrador\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tpintegrador\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tpintegrador\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tpintegrador\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tpintegrador\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\tpintegrador\app\Controllers\Login_controller.php(25): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(932): App\Controllers\Login_controller->auth()
#8 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login_controller))
#9 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\tpintegrador\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'valdivia_j' in C:\xampp\htdocs\tpintegrador\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\tpintegrador\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tpintegrador\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tpintegrador\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tpintegrador\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tpintegrador\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\tpintegrador\app\Controllers\Login_controller.php(25): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(932): App\Controllers\Login_controller->auth()
#7 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login_controller))
#8 C:\xampp\htdocs\tpintegrador\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tpintegrador\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-25 02:18:38 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'valdivia_j'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login_controller.php(25): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Login_controller->auth()
 7 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login_controller))
 8 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
